name: Run Selenium Script

on:
  schedule:
    - cron: '0 * * * *'  # This runs the script every hour
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  selenium:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out your repository content

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # You can specify the Python version you need

    - name: Install dependencies
      run: |
        pip install selenium
        sudo apt-get install -y chromium-chromedriver
        sudo apt-get install -y chromium-browser

    - name: Run Selenium Script
      run: |
        DISPLAY=:99 python hqb.py  # Run the script with headless Chromium
